---
title: "EuroFab"
subtitle: "European Urban Fabric Classification Using Artificial Intelligence"
# author: "Martin Fleischmann"
# institute: "Charles University"
# date: "today"
format:
    revealjs:
        theme: [default, ../assets/reveal.scss]
        logo: ../assets/icon.svg
        menu: false
        transition: slide
        navigation-mode: linear
        controls-layout: edges
        progress: true
        include-in-header: ../assets/font.html
        embed-resources: true
        title-slide-attributes:
            data-background-image: ../assets/full_logo.svg
            data-background-size: 20%
            data-background-position: 50% 90%
---

# Project introduction

---

::: {.r-fit-text .absolute top=39%}
structure of human
settlements
:::

::: aside
[explainable data science]{.fragment .fade-in}
[ | EO]{.fragment .fade-in}
[ | state-of-the-art AI]{.fragment .fade-in}
:::

::: {.fragment .fade-in}
temporal dimension
:::

---

## Why urban fabric {.question}

There are currently very few instances of detailed, consistent and scalable measurements of urban fabric, and virtually none of them provide insight into its change over time


---
EuroFab paves the road for a world where stakeholders, from local authorities to supranational organisations, are able to track and monitor the pattern of urban development in detail directly relevant for planning and at scale.

## Direct contributions

- Data-Driven Decision Making
- Sustainable Urban Development
- Climate Change Mitigation
- Energy Efficiency and Renewable Energy
- Nature-Based Solutions and Biodiversity
- Remote sensing for land use
- Computational and EO capability

## High-level objectives

Strengthen UK and Czech national capability to exploit leading edge AI methods to integrate EO data and high-performance computing

Expand the integration and uptake of EO-derived information

## Technical objectives

- Specify, develop and validate innovative methods that can be scaled from laptop to HPC to integrate raster (satellite) and vector data in rich and explainable characterisations of urban fabric
- Test the comparative performance of transformer-based (foundation) vision models against the baseline of convolution-based neural networks
- Evaluate the selected vision models on two European regions
- Develop open-source software, algorithms and open datasets that ensure the sustainability and usability of the project outputs beyond the initial funding period
- Create the roadmap for a large-scale inference chain (i.e. covering all of Europe or parts of the globe) for the capability being developed

## State of the Art

## Proposed approach

### Morphometrics

### Satellite

### How does it compare to existing products

## Targeted users

## First iteration

- input datasets
- envisaged system
- Develop a space-time dataset of urban fabric in Great Britain
- Develop a protocol, tools and models for homogenisation of morphometric classification.
- Stakeholder consultation and co-production ensuring applicability and commercialisation of the data products [Claudia]